scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleInsignia, function (sprite, location) {
    music.stopAllSounds()
    music.baDing.play()
    game.showLongText("\"ΜΠΡΑΒΟ! ΤΕΛΕΙΩΣΕΣ ΤΟΝ ΛΑΒΥΡΙΝΘΟ! ΒΑΛΕ ΤΗΝ ΛΕΞΗ \"ΓΗ\" ΓΙΑ ΝΑ ΠΕΡΑΣΕΙΣ\"", DialogLayout.Center)
})
scene.setBackgroundColor(2)
tiles.setTilemap(tilemap`level1`)
let mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    .........ffffff.........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbfb....bfbfbf....
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
tiles.placeOnTile(mySprite, tiles.getTileLocation(2, 2))
scene.cameraFollowSprite(mySprite)
